#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/book_panda?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1715
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update # 애플리케이션을 시작할 때마다 스키마를 업데이트하지 않도록 설정
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true # 올바른 속성 이름을 사용하여 설정 수정
#
#jwt:
#  header: Authorization
#  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
#  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
#  token-validity-in-seconds: 86400 # ttl (초)